spring.application.name=analyzer
spring.config.import=optional:configserver:
spring.cloud.config.fail-fast=false
spring.cloud.config.retry.useRandomPolicy=true
spring.cloud.config.retry.max-interval=6000
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.serviceId=config-server

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/analyzer
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

telemetry.analyzer.kafka.bootstrap-servers=localhost:9092
telemetry.analyzer.kafka.consumer.snapshot.topic=telemetry.snapshots.v1
telemetry.analyzer.kafka.consumer.snapshot.group-id=analyzer.snapshots
telemetry.analyzer.kafka.consumer.hub-events.topic=telemetry.hubs.v1
telemetry.analyzer.kafka.consumer.hub-events.group-id=analyzer.hub-events

grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enableKeepAlive=true
grpc.client.hub-router.keepAliveWithoutCalls=true
grpc.client.hub-router.negotiationType=plaintext
